---
# tasks file for isacadm
<<<<<<< HEAD
#
- name: Debug the isac_address
  debug:
    var: isac_address

- name: Create the backup directory
  file:
    path: /conf/backup
    state: directory

- name: Back-up the previous server.pem
  copy:
    src: /conf/server.pem
    dest: /conf/backup/server.pem.backup
    owner: sysadmin
    group: sysadmin
    mode: '0644'

- name: Update the certificate
  copy:
    src: "{{ role_path }}"/files/server.pem
    dest: /conf/server.pem
    owner: sysadmin
    group: sysadmin
    mode: '0644'
=======
##################################################################################################################################################################################
# Colect the facts of the target hosts
##################################################################################################################################################################################
- name: Collect only facts returned by facter
  setup:
    gather_subset:
      - '!all'
      - '!any'
      - facter

##################################################################################################################################################################################
# Create the Back-up directory
##################################################################################################################################################################################
- name: Create the Back-up directory
  file:
    path: ~/backup
    state: directory

##################################################################################################################################################################################
# Back-up the previous configuration for the certificats
##################################################################################################################################################################################
- name: Back-up previous configuration
  copy:
    src: /conf/*
    dest: ~/backup/
>>>>>>> 8313915bfd1aa37030b9cc7bf8f999cf3037a8a9


