---
# tasks file for isacadm
##################################################################################################################################################################################
# Colect the facts of the target hosts
##################################################################################################################################################################################
- name: Collect only facts returned by facter
  setup:
    gather_subset:
      - '!all'
      - '!any'
      - facter

##################################################################################################################################################################################
# Create the Back-up directory
##################################################################################################################################################################################
- name: Create the Back-up directory
  file:
    path: ~/backup
    state: directory

##################################################################################################################################################################################
# Back-up the previous configuration for the certificats
##################################################################################################################################################################################
- name: Back-up previous configuration
  copy:
    src: /conf/*
    dest: ~/backup/


